# Generated by Django 3.2.5 on 2021-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
                ('age', models.PositiveSmallIntegerField(blank=True, verbose_name='возраст')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
        ),
    ]
