# Generated by Django 3.2.5 on 2021-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=64, verbose_name='имя пользователя'),
            preserve_default=False,
        ),
    ]
